### ISSUE TITLE
Module build failed : Style Loader Invalid Options

### ISSUE THREAD

**Issue by NSaiRaghava** [kush-agra/react-horizontal-datepicker#2]
Hi,
I have installed horizontal date picker with command
      npm install react-horizontal-datepicker --save
followed the sample example from ReadMe
![Screenshot from 2020-01-22 18-50-35](https://user-images.githubusercontent.com/26787209/72897528-2ec7b100-3d48-11ea-8640-0a5426453ea2.png)
and when I run the project getting the following issue
![Screenshot from 2020-01-22 18-47-05](https://user-images.githubusercontent.com/26787209/72897561-42731780-3d48-11ea-8bef-63606c975c2e.png)
Can you help me, please
Please find my dependencies in package.json
![Screenshot from 2020-01-22 18-52-20](https://user-images.githubusercontent.com/26787209/72897639-6afb1180-3d48-11ea-9ad5-d1a5fd099c20.png)
Thanks.

**Comment by kush-agra** [comment]
Hello, I believe it's something about the css-loader, maybe due to it being an older version, not sure for now will see into it until then could you try manually adding the js and css from [src](https://github.com/kush-agra/react-horizontal-datepicker/tree/master/src) and see if that works

**Comment by NSaiRaghava** [comment]
I tried to import "react-horizontal-datepicker/dist/datepicker.css"
and import  './../../../node_modules/react-horizontal-datepicker/dist/datepicker.css'
but still, I got the same issue 

I am able to work with the plugin in CodeSandBox
https://codesandbox.io/s/clever-kilby-rjhc7
but it's not working in my project setup 

Is the issue because of the style-loader?
I am using  "style-loader": "0.23.1", version
Am I missing any dependency? @kush-agra

**Comment by kush-agra** [comment]
hmm! could you for now try getting the components [directly](https://github.com/kush-agra/react-horizontal-datepicker/tree/master/src/components) while I try to figure it out

**Comment by NSaiRaghava** [comment]
It works now, Thanks

**Comment by kush-agra** [comment]
:) it's supposed to work as an import too though, I'll try to figure how to get it to play nicely with css loaders, maybe a module css file is the answer? if anyone seeing this has any ideas, help would be appreciated ^^'
